name: bundle-release-gds-way

on:
  push:
    branches: [ master ]

  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Install-cf7-cli
        run: |
          wget -q -O - https://packages.cloudfoundry.org/debian/cli.cloudfoundry.org.key | sudo apt-key add -
          echo "deb https://packages.cloudfoundry.org/debian stable main" | sudo tee /etc/apt/sources.list.d/cloudfoundry-cli.list

          sudo apt-get update
          sudo apt-get install -y cf7-cli

      - name: bundle-gds-way
        run: |
          bundle install --without development
          bundle exec middleman build

      - name: deploy-to-paas
        env:
          CF_USERNAME: ${{ secrets.CF_EMAIL }}
          CF_PASSWORD: ${{ secrets.CF_PASSWORD }}
        run: |
          cf api https://api.cloud.service.gov.uk
          cf auth
          cf target -o gds-tech-ops -s docs

          cf push -f ./manifest.yml
